### ISSUE TITLE
Version for packages?

### ISSUE THREAD

**Issue by CCYChongyanChen** [sean-zhuh/SeqTR#11]
Dear author,
Could you please kindly share your versions for each of the following packages? 
torch, torchvision, mmdet, and mmcv-full

Thank you so much!

**Comment by sean-zhuh** [comment]
If I remember correctly, it would be the following:
torch: 1.10.0+cu113
mmcv-full: same as torch
mmdetection: 2.21.0
torchvision: 0.11.0
I expect no issues from installation as I install this github repo in August, 2022, so it's strange, the versions I used is different from those listed above. You can troubleshooting in mmdetection/mmcv installation issues. :)

**Comment by CCYChongyanChen** [comment]
Thanks for the info! 
For those who have a similar issue, I found the mmdet compatibility here:
 https://github.com/open-mmlab/mmdetection/blob/master/docs/en/compatibility.md.

**Comment by CCYChongyanChen** [comment]
BTW, the pytorch version have to be >=1.9.0
Otherwise you will have TypeError: SeqTR: SeqHead: AutoRegressiveTransformer: __init__() got an unexpected keyword argument 'batch_first'

The following versions work for me:
torch: 1.9.0+cu111;
torchvision: 0.10.0+cu111
mmcv-full:1..5.0
mmdet: 2.21.0


pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
pip install mmdet==2.21.0
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html
