### ISSUE TITLE
multi-task的配置文件

### ISSUE THREAD

**Issue by Azong-HQU** [sean-zhuh/SeqTR#13]
作者您好，我正在研读您的code，目前有两个问题存在一些疑问。

1.请问multi-task的训练是detection和segmentation两个任务统一训练吗？还是需要分开训呢？

2.在multi-task的配置文件中，比如 configs/seqtr/multi-task/seqtr_multi-task_refcocog-google.py，其中需要到 '../../_base_/datasets/multi-task/refcocog-google.py' 的配置文件，但在本项目中没有给出，请问作者会公开这部分的配置吗？或者您可以告诉我该如何更改配置吗？

**Comment by sean-zhuh** [comment]
1. 统一训，详见论文补充材料中的图7
2. 配置文件和configs/_base_/datasets/detection或segmentation下的文件基本一致，我已推到仓库中。

**Comment by Azong-HQU** [comment]
感谢作者！
