### ISSUE TITLE
Customized dataset?

### ISSUE THREAD

**Issue by CCYChongyanChen** [sean-zhuh/SeqTR#14]
Hi, thanks for the awesome work.
Could I ask how could we obtain the token_to_ix.pkl, ix_to_token.pkl, and the word_emb.npz to generate customized dataset?
Thank you so much!

**Comment by sean-zhuh** [comment]
Hi, you can check seqtr/datasets/utils/tokenize function for generating these files, in general, you need to provide a json file that stores all the necessary information just like instance.json that I provided.

**Comment by CCYChongyanChen** [comment]
Thanks!
