### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by chenjianqiang199526** [sean-zhuh/SeqTR#3]
a great job,can you provide the pretrained model?

**Comment by sean-zhuh** [comment]
Yes, I have got some of the pre-trained model checkpoints from the GPU server. I'm ready to update the code and provide the model in a few days.

**Comment by sean-zhuh** [comment]
Thanks for your patience, part of the checkpoints have been uploaded. I'll re-train those haven't been uploaded cause there is a download hash md5 error when my collaborators download them for me from the GPU server.
