### ISSUE TITLE
指标对不上

### ISSUE THREAD

**Issue by chenjianqiang199526** [sean-zhuh/SeqTR#4]
你好，train_log里的valid的指标和单独跑test.py使用val的数据集出来的指标好像对不上

**Comment by sean-zhuh** [comment]
哪个模型，硬件配置是什么。

**Comment by chenjianqiang199526** [comment]
![深度截图_选择区域_20220525180438](https://user-images.githubusercontent.com/34065231/170237503-53a3704e-5e88-4228-8604-6542c2d9c1d9.png)
我随机选了一点数据用train训练了之后在用test测试的，机器配置也是v100.8卡

**Comment by sean-zhuh** [comment]
只上传了RefCOCO/+/g的checkpoint，没有上传Flickr30k和ReferItGame的哈，你是用RefCOCO的checkpoint测Flickr30k。
![170237503-53a3704e-5e88-4228-8604-6542c2d9c1d9](https://user-images.githubusercontent.com/29118637/170239468-487ef1c1-f2a2-4afc-8fa2-149648bd30b0.png)

**Comment by chenjianqiang199526** [comment]
> 只上传了RefCOCO/+/g的checkpoint，没有上传Flickr30k和ReferItGame的哈，你是用RefCOCO的checkpoint测Flickr30k。 ![170237503-53a3704e-5e88-4228-8604-6542c2d9c1d9](https://user-images.githubusercontent.com/29118637/170239468-487ef1c1-f2a2-4afc-8fa2-149648bd30b0.png)

你们发的ckpt是能对上的，上面这个是我自己拿数据集训得，不过是多卡的，是不是必须要拿单卡finetune？

**Comment by sean-zhuh** [comment]
建议单卡，多卡测试可能会有点问题。

**Comment by chenjianqiang199526** [comment]
好的，多谢。
