### ISSUE TITLE
Training with 16GB

### ISSUE THREAD

**Issue by pqviet** [sean-zhuh/SeqTR#5]
Thanks for your sharing code.
I have 8 GPUs with 16 GB each. How can I train and evaluate SeqTR?

**Comment by sean-zhuh** [comment]
Setting the batch size to 64 would be fine, the performance is expected to drop 1 point, or you can do DDP training using 2 gpus cards while still maintaining the batch size to 128.

**Comment by pqviet** [comment]
Do you mean I can use the following command to perform training ?
bash tools/dist_train.sh configs/seqtr/segmentation/seqtr_mask_[DATASET_NAME].py --cfg-options ema=True

**Comment by sean-zhuh** [comment]
You can use the following command:

`CUDA_VISIBLE_DEVICES=0,1 bash tools/dist_train.sh configs/seqtr/segmentation/seqtr_mask_[DATASET_NAME].py 2 --cfg-options ema=True data.samples_per_gpu=64`

or using the single gpu command:

`python tools/train.py configs/seqtr/segmentation/seqtr_mask[DATASET_NAME].py --cfg-options ema=True data.samples_per_gpu=64`

**Comment by pqviet** [comment]
Thank you very much
