### ISSUE TITLE
mixed datasets

### ISSUE THREAD

**Issue by MasterBin-IIAU** [sean-zhuh/SeqTR#8]
Hi, thanks for the awesome work. 
Datasets and most annotations can be normally downloaded following the README. But I did not find **mixed** in the provided google drive [link](https://drive.google.com/drive/folders/1IXnSieVr5CHF2pVJpj0DlwC6R3SbfolU). Have I missed something? Thanks in advance.

**Comment by sean-zhuh** [comment]
Sorry for the inconsistency here, the mixed dataset is pretraining-vg in google drive, I've renamed it to mixed.

**Comment by MasterBin-IIAU** [comment]
Thanks for your reply :)
