### ISSUE TITLE
Memory and BatchSize

### ISSUE THREAD

**Issue by MasterBin-IIAU** [sean-zhuh/SeqTR#9]
Hi, thanks for the wonderful work. 
I am curious about why SeqTR is so memory-efficient. As shown in the config file, SeqTR is trained with a batch size of 128 on a single 32GB GPU! However, for object detectors like DETR, the batch size on each GPU is quite limited. Could you please give some insights about this? Thanks in advance.

**Comment by sean-zhuh** [comment]
1. Image Resolution: For visual grounding (VG), the image resolution ranges from 416 x 416 - 640 x 640, For object detection (OD), the resolution is 1333 x 800 in general, or more
2. Model Architecture: DarkNet-53 (in YOLOv3) is used in VG, which compares favorably over ResNet in OD, see the figure on the ImageNet Classificaiton task.
<img width="572" alt="DarkNet" src="https://user-images.githubusercontent.com/29118637/183427013-22f6c8b9-06c2-4a77-bc1f-f7b35f138774.png">
3. the hidden dimension of transformer in SeqTR is set to 256, and the FFN dimesion is 1024, while that of DETR is 512 and 2048, respectively, besides, we only use 3 decoders compared to 6 decoders in DETR.

**Comment by MasterBin-IIAU** [comment]
Thanks for your reply. It does make it reasonable :)
